### ISSUE TITLE
No such file or directory during: source bin/sharpy_vars.sh

### ISSUE THREAD

**Issue by chanjiacheng** [ImperialCollegeLondon/sharpy#233]
My system is ubuntu 22.04 and I did follow the sharpy installation guide here: https://ic-sharpy.readthedocs.io/en/dev_doc/content/installation.html

However when it comes to the step of `source bin/sharpy_vars.sh`, it seems like I don't have such file in my directory.

I have tried to re-install the sharPy but the issue persists, can someone assist if I miss out any step?

Appreciate your help in this matter. Regards.

**Comment by kccwing** [comment]
Hello @chanjiacheng!
I believe you have accidentally referred to outdated documentation - you are reviewing the docs for branch dev_doc. Kindly use this link https://ic-sharpy.readthedocs.io/en/latest/ for the updated installation instructions which involves pip rather than the outdated bash file. Let us know if you encounter further trouble, thanks!
