### ISSUE TITLE
run_theo_freq.py fails in Docker container

### ISSUE THREAD

**Issue by petebachant** [ImperialCollegeLondon/sharpy#37]
For https://github.com/openjournals/joss-reviews/issues/1885.

I'm assuming one would want to be able to run the example cases from the Docker container.

Firstly, I had to install matplotlib, since it's imported in the script. After that, I get the error:

```
Traceback (most recent call last):
  File "run_theo_freq.py", line 236, in <module>
    Sol = lin_aeroelastic.LinAeroEla(data0)
  File "/sharpy/sharpy/linear/src/lin_aeroelastic.py", line 118, in __init__
    self.lingebm_str = lingebm.FlexDynamic(self.tsstr, structure, beam_settings)
  File "/sharpy/sharpy/linear/src/lingebm.py", line 119, in __init__
    self.Nmodes = self.settings['num_modes']
KeyError: 'num_modes'
```

**Comment by fonsocarre** [comment]
Thanks @petebachant, you are 100% right. This script is old and somehow it survived the clean up. @ngoiz will check it, as the linear part is his stuff. 

Concerning the matplotlib dependency. It is 50/50 in purpose. I decided when releasing v1.0.0 to remove matplotlib as a required dependency, specially for the docker image, to keep it light and compatible with headless machines. That's why the `utils/environment_linux.yml` has it, but `enviroment_minimal.yml` (the one for the Docker build) does not have it. Unfortunately, as I said, this script slipped through the cracks. My advice to @ngoiz is to wrap the plotting bits in a `try except` block (including the import) and use matplotlib if available, if not, print a warning and keep running.

**Comment by petebachant** [comment]
That sounds reasonable to me!

**Comment by ngoiz** [comment]
Thanks, Pete, for going through this. Indeed this is a legacy test case that slipped through the cracks and made it onto the release build. So the first step is that it will be removed from the release build and then I will incorporate it as a proper test case (or even tutorial since it is a nice example). PR coming soon for this.

And I agree on the matplotlib issues, those will be fixed as well with the try except option.

**Comment by fonsocarre** [comment]
With #38 and #41, plus commit af5964a2f8a7a1e133c0948cb2fdeb5cb5c46568 this is now fixed.
