### ISSUE TITLE
Hinge definition for control surface

### ISSUE THREAD

**Issue by scolonia** [ImperialCollegeLondon/sharpy#8]
The possibility to specify hinges for control surfaces rotations should be added

**Comment by fonsocarre** [comment]
Fixed in commit 705fb660b2358656e36635bcd5c1ae4f091255cb. The `test/coupled/dynamic/hale` case is updated to reflect the interface. Take into account that the hinge parameter is only valid for surfaces where the whole chord is defined as control surface in order to avoid discontinuities in the panelling.
