### ISSUE TITLE
Plunging Motion

### ISSUE THREAD

**Issue by FrederickSnopl** [ImperialCollegeLondon/sharpy#98]
Hi, I'm doing some research for the University of Alabama in Huntsville and was wondering if this software had a set up way to model plunging motion of an airfoil. I've run through the Goland wing example as it was the most similar but nothing struck me as though it would fit for this application. Any help would be appreciated.

**Comment by ngoiz** [comment]
Hi Frederick,

Most likely you will need to use the linear modules in SHARPy to achieve what you want to do. 

You would need to make use of the `LinearAssembler` and set-up the problem like the example of the [Horten flying wing](https://ic-sharpy.readthedocs.io/en/master/content/example_notebooks/linear_horten.html). You need to set it up with the rigid body degrees of freedom in order to be capable of simulating the plunge of the whole wing.

However, since you just want the plunge, you can use the setting `remove_dofs` in the [linear beam system](https://ic-sharpy.readthedocs.io/en/master/includes/linear/assembler/linearbeam/LinearBeam.html) to get rid of `W` and `orient` (the rotational degree of freedom and the orientation of the reference node). If you want to keep it rigid you can also get rid of `eta`. That will assemble the system for you without those degrees of freedom.

You can then save the resulting aeroelastic state space for your own post-process or use our own. I think you would be interested in the `FrequencyResponse` one, once you identify the input for the plunge you can check the corresponding transfer function. The inputs and outputs are ordered as in [here](https://ic-sharpy.readthedocs.io/en/master/includes/linear/assembler/linearaeroelastic/LinearAeroelastic.html), which I understand may be confusing so let us know if you decide to take this route and need further help identifying inputs and outputs.

Regards,
Norberto

**Comment by FrederickSnopl** [comment]
Hey Noberto,

Thanks for the help, I've been working with that for a little bit but have run into a problem.
Changing the remove_dofs setting to include W and orient causes an error in lindynamicsim. The debugger (Pdb) opens automatically when line 117 is run and when I tell it to continue I get "ValueError: shapes (2124,884) and (893,) not aligned: 884 (dim 1) != 893 (dim 0)." If I change the remove_dofs setting back to empty then it works again. I've tried W and orient individually but I get a similar error (the dims that don't match can change slightly). I posted the full error down below. Is there anything I can do to mitigate this?

Also is there a way to get force outputs in the time domain? The way the force outputs work in the linear_horten case doesn't seem to be time dependent but that would be really helpful for me.

Thanks,
Fred

Full error here (the c was input by me to continue the program):  
> /home/fss0003/sharpy/sharpy/solvers/lindynamicsim.py(117)run()
-> try:
(Pdb) c
Solving linear system using scipy...
Exception raised, writing error log in /home/fss0003/sharpy/cases/coupled/linear_horten/cases/horten_euler_u_inf2800_M4N11Msf5_rho1.0/output/horten_euler_u_inf2800_M4N11Msf5_rho1.0/error.log
Traceback (most recent call last):
  File "/home/fss0003/sharpy/bin/sharpy", line 9, in <module>
    data = sharpy.sharpy_main.main(sys.argv)
  File "/home/fss0003/sharpy/sharpy/sharpy_main.py", line 124, in main
    raise e
  File "/home/fss0003/sharpy/sharpy/sharpy_main.py", line 100, in main
    data = solver.run()
  File "/home/fss0003/sharpy/sharpy/solvers/lindynamicsim.py", line 117, in run
    try:
  File "/home/fss0003/anaconda3/envs/sharpy_env/lib/python3.7/site-packages/scipy/signal/ltisys.py", line 439, in output
    return dlsim(self, u, t, x0=x0)
  File "/home/fss0003/anaconda3/envs/sharpy_env/lib/python3.7/site-packages/scipy/signal/ltisys.py", line 3368, in dlsim
    np.dot(system.B, u_dt[i, :]))
  File "<__array_function__ internals>", line 6, in dot
ValueError: shapes (2124,884) and (893,) not aligned: 884 (dim 1) != 893 (dim 0)

**Comment by ngoiz** [comment]
Hi Fred,

The dimension mismatch is occurring because the linearised system, when using `remove_dofs` loses these inputs and outputs as well. To solve this, you need to adjust your input vector `u` to not include those degrees of freedom either. 

That said, a small disclaimer. The `LinDynamicSim` solver is very basic and seldom used since we normally don't do linear time domain simulations and so we typically use it to postprocess the linear results and visualise them in Paraview. Thus, there might be the odd bug here and there, in particular if using ROMs or removing degrees of freedom as you have seen.

I would suggest that if you want to do linear simulations either a) save the state-space and simulate externally (maybe using matlab) or b) try and modify `LinDynamicSim` (in the end it is just a scipy wrapper) if you are very keen on the Paraview output. 

With respect to the Horten's output forces not changing with time I'm not sure I follow. With the frequency response data you should be able to capture the output for any desired input frequency, or you could get the time domain representation doing a simulation to a sinusoidal input of a known frequency, the result would be identical. 

Hope this helps,

Norberto
